version: '3'

services:
    mariadb:
      container_name: mariadb
      networks:
        - inception
      build:
        context: requirements/mariadb
        dockerfile: Dockerfile
      env_file: .env
      volumes:
        - mariadb_data:/var/lib/mysql
      restart: on-failure
      expose:
        - "3306"

    nginx:
      container_name: nginx
      volumes:
        - wordpress_data:/var/www/html
      networks:
        - inception
      depends_on:
        - wordpress
      build:
        context: requirements/nginx
        dockerfile: Dockerfile
      env_file : .env
      ports:
        - "443:443"
      restart: on-failure

    wordpress:
      container_name: wordpress
      env_file: .env
      volumes:
        - wordpress_data:/var/www/html
      networks:
        - inception
      build:
        context: requirements/wordpress
        dockerfile: Dockerfile
      depends_on:
        - mariadb
      expose:
        - "9000"
      restart: on-failure
  
volumes:
  wordpress_data:
    driver: local
    driver_opts:
      type: 'none'
      o: 'bind'
      device: '/home/phabets/data/wordpress'
  mariadb_data:
    driver: local
    driver_opts:
      type: 'none'
      o: 'bind'
      device: '/home/phabets/data/mariadb'
networks:
  inception:
    driver: bridge



